Repository Jordanimaal/projectAWS, pull requests merged in 2022-04, with the labels that each got.

#4 Fix : DynamoDB missing fields
  babyfoot-IoT/samconfig.toml
  babyfoot-IoT/template.yaml
Labels: bug

#5 définition des tables
  babyfoot - dico de données et pricing
Labels: documentation

#7 fix(tableName): add TableName to DynamoDB Table
  .gitignore
  README.md
  babyfoot - dico de données et pricing
  babyfoot-IoT/template.yaml
Labels: bug, documentation

#8 IoT Stack: Add output for web interface
  babyfoot-IoT/template.yaml
Labels: enhancement

#9 Infra: add secondary index to dynamodb
  babyfoot-IoT/template.yaml
Labels: enhancement

#10 Doc: readme
  README.md
Labels: documentation

#11 Fix doc
  README.md
Labels: documentation
